name: delayed
on:
  pull_request:
    types: [synchronize]

jobs:
  checkrun-timechart:
    runs-on: ubuntu-latest
    steps:
      - name: wait
        uses: "WyriHaximus/github-action-wait-for-status@4c9e58820905eb246e88a413c39a9104cccf7e80"
        with:
          ignoreActions: checkrun-timechart
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: checkrun-timechart
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.event.pull_request.head.sha }}"
          TRACE_START: "${{ github.event.pull_request.updated_at }}"

