name: test-push
on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo examples should be visible

  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo duplicate job names should not cause failure

  checkrun-timechart:
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: checkrun-timechart-github
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.sha }}"
          TRACE_START: "${{ github.event.repository.pushed_at }}"
