name: test
on:
  push:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - closed
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  slow-thing:
    runs-on: ubuntu-latest
    steps:
      - run: echo examples should be visible
      - run: sleep 5

  docker:
    runs-on: ubuntu-latest
    steps:
      - run: echo duplicate job names should not cause failure

  push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: checkrun-timechart-github
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BT_DEBUG: "1"

  pull_request:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v2
      - name: checkrun-timechart-github
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.event.pull_request.head.sha }}"
          TRACE_START: "${{ github.event.pull_request.updated_at }}"
